---
title: "home.ze"
subtitle: "dashboard"
icon: "fas fa-skull-crossbones"
header: true
columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true
links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/stefanopulze"
    target: "_blank"

# Services
services:
  - name: "Network"
    icon: "fas fa-network-wired"
    items:
      - name: "Unifi Controller"
        icon: "fas fa-network-wired"
        subtitle: "Network manager"
        tag: "network"
        url: "https://192.168.1.40:8443/manage"
        target: "_blank"
      - name: "Pi-hole"
        icon: "fas fa-heartbeat"
        subtitle: "Pi-hole admin"
        tag: "network"
        url: "http://192.168.1.40:8082/admin"
        target: "_blank"
        type: "PiHole"
      - name: "Switch"
        subtitle: "ZyXel GS1900-24"
        icon: "fas fa-server"
        tag: "network"
        url: "http://192.168.1.2"
        target: "_blank"
  - name: "Service"
    icon: "fas fa-chart-line"
    items:
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Network manager"
        tag: "monitoring"
        url: "http://192.168.1.40:3000"
        target: "_blank"
      - name: "Duplicati"
        logo: "assets/tools/duplicati.png"
        subtitle: "Backup"
        url: "http://duplicati.home.stefanopulze.com"
        target: "_blank"
      - name: "rTorrent"
        subtitle: "Torrent downloader"
        logo: "assets/tools/rtorrent.png"
        url: "http://192.168.1.230"
        target: "_blank"

  - name: "Application"
    icon: "fas fa-heartbeat"
    items:
      - name: "Dahua NVR"
        subtitle: "Home camera"
        icon: "fas fa-video"
        tag: "invoice"
        url: "https://192.168.1.5"
        target: "_blank" # optional html a tag target attribute
      - name: "Popay"
        subtitle: "Invoice manager"
        icon: "fas fa-file-invoice-dollar"
        tag: "invoice"
        url: "http://192.168.1.40:3000"
        target: "_blank" # optional html a tag target attribute