version: "3"

services:
  # Dashboard
  homer:
    image: b4bz/homer:latest
    restart: unless-stopped
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /opt/home/config/homer:/www/assets
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.homer.tls.certresolver=cloudflare"

  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /opt/home/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /opt/home/config/mosquitto/passwd:/etc/mosquitto/passwd
      
  # Docker registry
  registry:
    image: registry:2
    restart: unless-stopped
    environment:
      - REGISTRY_DELETE_ENABLED=true
    volumes:
      - /opt/storage/registry:/var/lib/registry
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.entrypoints=https"
      - "traefik.http.routers.registry.rule=Host(`registry.$DOMAIN`)"
      - "traefik.http.routers.registry.tls.certresolver=cloudflare"
    
  unifi:
    image: lscr.io/linuxserver/unifi-controller
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
      - MEM_STARTUP=1024M #optional
    volumes:
      - /opt/storage/unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.entrypoints=https"
      - "traefik.http.routers.unifi.rule=Host(`unifi.$DOMAIN`)"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
    networks:
      - proxy
    
  # Monitoring
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - /opt/home/config/prometheus:/etc/prometheus
    
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /opt/home/config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - storage-grafana:/var/lib/grafana
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.$DOMAIN`)"
      - "traefik.http.routers.grafana.tls.certresolver=cloudflare"

volumes:
  storage-grafana:

networks:
  proxy:
    external: true
